version: '3.8'
services:
  movies:
    image: vikram317/paytmmovies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3

  train:
    image: vikram317/paytmtrain:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3

  dth:
    image: vikram317/paytmdth:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3

  recharge:
    image: vikram317/paytmrc:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3

