version: '3.8'
services:
  movies:
    image: vikram317/paytmmovies:latest
    ports:
      - "85:80"
    deploy:
      replicas: 3
    volumes:
      - "movies"
  train:
    image: vikram317/paytmtrain:latest
    ports:
      - "86:80"
    deploy:
      replicas: 3
    volumes:
      - "train"
  dth:
    image: vikram317/paytmdth:latest
    ports:
      - "87:80"
    deploy:
      replicas: 3
    volumes:
      - "dth"
  rc:
    image: vikram317/paytmrc:latest
    ports:
      - "88:80"
    deploy:
      replicas: 3
    volumes:
      - "rc"
